# Generated by Django 4.2 on 2023-04-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('decription', models.TextField()),
                ('rate', models.FloatField()),
                ('created_date', models.DateField(auto_now=True)),
                ('modified_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
