# Generated by Django 4.2 on 2023-04-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
