# Generated by Django 4.2 on 2023-04-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
